dist: trusty
sudo: false
group: beta
language: ruby
cache: bundler
script: "TESTOPTS=-v bundle exec rake test"
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-9.0.5.0
  - jruby-head
  - rbx-3
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-3
    - rvm: ruby-head
